services:
  backend:
    build: backend
    ports:
      - 8080
    environment:
      - POSTGRES_DB=greetingsdb
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=springboot-backend
      - SPLUNK_PROFILER_ENABLED=true
      - SPLUNK_PROFILER_LOGS_ENDPOINT=http://otel-collector:4317
      - SPLUNK_METRICS_ENABLED=true
      - SPLUNK_METRICS_ENDPOINT=http://otel-collector:9943
    networks:
      - spring-postgres
  db:
    image: postgres
    restart: always
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init-db:/docker-entrypoint-initdb.d
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=greetingsdb
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432

  loadgen:
    image: locustio/locust
    ports:
     - 8089
    volumes:
      - ./loadgen:/mnt/locust
    depends_on:
      - backend
    command: -f /mnt/locust/locust-loadgen.py --headless -H http://backend:8080 -u 2 -r 1
    networks:
      - spring-postgres
  
  otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:0.40.0
    env_file:
      # copy the example.env file and save it as .env and change the values as appropriate
      - .env
    volumes:
       - "./otel-collector/gateway_config.yaml:/etc/otel/collector/gateway_config.yaml"
    ports:
      - "4317"
      - "8006"
    networks:
      - spring-postgres
    depends_on:
      - db

volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  spring-postgres:
