services:
  nginx-flask-proxy:
    hostname: nginx-flask-proxy
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=backend:9091  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80
    depends_on:
      - backend
  backend:
    build: flask
    environment: 
      - FLASK_SERVER_PORT=9091
      - OTEL_SERVICE_NAME=flask-backend
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    volumes:
      - ./flask:/src
    depends_on:
      -  mongo  
  mongo:
    hostname: flask-mongo
    image: mongo

  loadgen:
    image: locustio/locust
    ports:
     - 8089
    volumes:
      - ./loadgen:/mnt/locust
    command: -f /mnt/locust/locust-loadgen.py --headless -H http://nginx-flask-proxy -u 4 -r 1

  otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:0.41.0
    hostname: nginx-flask-mongodb-example.tubalinal.io
    env_file:
      - .env
    volumes:
       - "./otel-collector/gateway_config.yaml:/etc/otel/collector/gateway_config.yaml"
    ports:
      - "4317"
      - "8006"

