services:
  backend:
    build: backend
    restart: always
    secrets:
      - db-password
    depends_on: 
      - db
    environment:
      - ASPNETCORE_URLS=http://+:8000
#    depends_on:
#      db:
#        condition: service_healthy
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

  nginx-proxy:
    build: proxy
    hostname: nginx-proxy-prod-0.tubalinal.io
    ports:
      - 80
    depends_on: 
      - backend

  loadgen:
    image: locustio/locust
    ports:
     - 8089
    volumes:
      - ./loadgen:/mnt/locust
    command: -f /mnt/locust/locust-loadgen.py --headless -H http://nginx-proxy -u 4 -r 1
  
  otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:0.37.1
    hostname: nginx-aspnet-mysql-example.tubalinal.io
    env_file:
      - .env.us0
    volumes:
       - "./otel-collector/gateway_config.yaml:/etc/otel/collector/gateway_config.yaml"
    ports:
      - "4317"
      - "8006"


volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
